apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-server-virtual-service
  namespace: k8s-grpc-istio-test
spec:
  hosts:
    - "istio-echo-backend"
  http:
    - match:
        - port: 4004
      route:
        - destination:
            host: echo-backend-service
            port:
              number: 4004
